version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "none"
  magpie:
    build: .
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - MAGPIE_DISCOVERY=${MAGPIE_DISCOVERY}
      - MAGPIE_POLICY=${MAGPIE_POLICY}
      - MAGPIE_DMAP=${MAGPIE_DMAP}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
      - "pg"
  pg:
    image: postgres:13.3
    ports:
      - "25432:5432"
    logging:
      driver: "none"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  dmap-predictions:
    image: quay.io/openraven/dmap-predictions:latest
    ports:
      - "10234:10234"
    logging:
      driver: "none"
